services:
  solarx-dwh:
    build: .
    container_name: solarx-dwh
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    # ports:
    #   - '3306:3306'
    volumes:
      - ./dwh-schema:/docker-entrypoint-initdb.d
      - .:/dwh
      - solarx-dwh:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro" 
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - solarx-network


  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: solarx-dwh-phpmyadmin

    ports:
      - 801:80

    environment:
      - PMA_ARBITRARY=1
    
    networks:
      - solarx-network

    restart: unless-stopped


volumes:
  solarx-dwh:
    name: solarx-dwh
  
networks:
  solarx-network:
    name: solarx-network